# Generated by Django 3.2.5 on 2022-09-21 21:05

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=75)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Collection Agency', max_length=75, verbose_name='Agency Name')),
                ('unique_id', models.CharField(max_length=11)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Decribe your Agency')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Agencys Phone Number', max_length=128, region=None, verbose_name='Agency Phone Number')),
                ('email', models.EmailField(max_length=75, verbose_name='Agency Email')),
                ('price', models.CharField(blank=True, help_text='Set your Pricing for Unit Items e.g 1000/= per Kg', max_length=75)),
                ('logo', models.ImageField(upload_to='Images/Agency/logos', verbose_name='Agency logo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='accounts.collectionagentprofile')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.address')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='eWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(help_text='Describe your Item.', verbose_name='Item Description')),
                ('phone_contact', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone Number to link up for the Item', max_length=128, region=None, verbose_name='Contact Phone')),
                ('email', models.EmailField(help_text='Email linked to link up for the Item', max_length=75, verbose_name='Contact Email')),
                ('status', models.CharField(choices=[('picked', 'Picked'), ('pending', 'Pending')], default='Pending', help_text='Designate if the the item was picked or not', max_length=25)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(help_text='Please select the location of the Item', on_delete=django.db.models.deletion.CASCADE, to='agency.address', verbose_name='Item Address')),
                ('agent', models.ForeignKey(help_text='Choose an Agent to Pick Up your Item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.agency', verbose_name='Collection Agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'eWaste',
            },
        ),
        migrations.CreateModel(
            name='eWasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eWaste Category',
                'verbose_name_plural': 'eWaste Categories',
            },
        ),
        migrations.CreateModel(
            name='eWasteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload an Image for the eWaste', upload_to='Images/eWaste', verbose_name='eWaste Image')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ewaste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.ewaste')),
            ],
            options={
                'verbose_name': 'eWaste Image',
                'verbose_name_plural': 'eWaste Images',
            },
        ),
        migrations.AddField(
            model_name='ewaste',
            name='ewaste',
            field=models.ForeignKey(help_text='Select the eWaste you want to upload', on_delete=django.db.models.deletion.CASCADE, to='agency.ewastecategory', verbose_name='Select eWaste'),
        ),
    ]
