# Generated by Django 3.2.5 on 2022-09-23 07:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='tranport_fee',
            field=models.CharField(blank=True, help_text='Set your Transport Fee for Unit Items e.g 1000/= per Km', max_length=75),
        ),
        migrations.AddField(
            model_name='ewaste',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Weight in Kilos', verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ewaste',
            name='address',
            field=models.ForeignKey(help_text='Please select your Division', on_delete=django.db.models.deletion.CASCADE, to='agency.address', verbose_name='City Division'),
        ),
        migrations.CreateModel(
            name='SubAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=75)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.address')),
            ],
            options={
                'verbose_name': 'Sub Address',
                'verbose_name_plural': 'Sub Addresses',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ewate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.ewaste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='ewaste',
            name='sub_address',
            field=models.ForeignKey(blank=True, help_text='Please select the location of the Item', null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.subaddress', verbose_name='Address in Division'),
        ),
    ]
