# Generated by Django 3.2.5 on 2022-09-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20220923_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='ewate',
            new_name='ewaste',
        ),
    ]
