# Generated by Django 3.2.5 on 2022-09-23 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_rename_ewate_comments_ewaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewaste',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Weight in Kilos', validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Quantity'),
        ),
    ]
